name: 🐞 Bug Report
description: Report a reproducible bug or unexpected behavior
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Please describe the issue clearly, including reproduction steps and environment details.
  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: A concise description of the bug.
      placeholder: e.g. "Navigation bar disappears on scroll"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide numbered steps to reproduce the issue.
      placeholder: |
        1. Go to...
        2. Click...
        3. Observe...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What did you expect to happen?
  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        - OS: macOS / Windows / Linux
        - Browser: Chrome 108
        - Node: v18
  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: I have searched existing issues and found no duplicate.
          required: true
